version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: desafio7-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: desafio7
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: